apiVersion: v1
kind: Pod
metadata:
    name: ngipod
spec:
   containers:
    - name: mycontainer
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: myvol
   volumes:
       - name: myvol
         persistentVolumeClaim:
            claimName: mypvc



- Create pods for this files:
kubectl apply -f pv.yml
kubectl apply -f pvc.yml
kubectl apply -f pod.yml
- To view list of PV:
kubectl get pv
- To view list of PVC:
kubectl get pvc
- To view list of Pods:
kubectl get pods